name: Build v0.0.0-1.19+build.1

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  java_ver: "19"
  ver: "v0.0.0 MCV-1.19 Fabric"
  tag: "0.0.0-1.19+build.1"
  
jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, '[skip]') }}

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: validate gradle wraper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java_ver }}
          distribution: 'temurin'

      - name: make gradle wrapper exe
        run: chmod +x ./gradlew

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: build/libs/*.jar
          retention-days: 1

  release:
    if: ${{ !contains(github.event.head_commit.message, '[skip]') }}

    needs: [ build ]

    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: download
        uses: actions/download-artifact@v4

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          name: Unknown Mod ${{ env.ver }}
          tag_name: ${{ env.tag }}
          body_path: ${{ github.workspace }}/changelog.md
          draft: true
          generate_release_notes: true
          files: |
            jar/*.jar